#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const readline = require('readline');

// Colors for console output
const colors = {
  reset: '\x1b[0m',
  bright: '\x1b[1m',
  red: '\x1b[31m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  magenta: '\x1b[35m',
  cyan: '\x1b[36m'
};

function log(message, color = 'reset') {
  console.log(`${colors[color]}${message}${colors.reset}`);
}

function createInterface() {
  return readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });
}

function question(rl, query) {
  return new Promise((resolve) => {
    rl.question(query, resolve);
  });
}

async function setupMpesa() {
  log('🚀 UniStay M-Pesa Integration Setup', 'bright');
  log('=====================================', 'bright');
  log('');

  const rl = createInterface();

  try {
    log('This script will help you configure M-Pesa integration for UniStay.', 'cyan');
    log('You will need your M-Pesa API credentials from Safaricom Developer Portal.', 'cyan');
    log('');

    // Check if .env file exists
    const envPath = path.join(process.cwd(), '.env');
    const envExists = fs.existsSync(envPath);

    if (envExists) {
      log('⚠️  .env file already exists. This will update your existing configuration.', 'yellow');
      const overwrite = await question(rl, 'Do you want to continue? (y/N): ');
      if (overwrite.toLowerCase() !== 'y' && overwrite.toLowerCase() !== 'yes') {
        log('Setup cancelled.', 'red');
        rl.close();
        return;
      }
    }

    log('📝 Please provide your M-Pesa API credentials:', 'blue');
    log('');

    const consumerKey = await question(rl, 'M-Pesa Consumer Key: ');
    const consumerSecret = await question(rl, 'M-Pesa Consumer Secret: ');
    const shortcode = await question(rl, 'M-Pesa Shortcode (Paybill/Till Number): ');
    const passkey = await question(rl, 'M-Pesa Passkey: ');
    
    log('');
    log('🌐 Application Configuration:', 'blue');
    const baseUrl = await question(rl, `Application Base URL (default: https://www.unistay.co.ke): `) || 'https://www.unistay.co.ke';
    
    log('');
    log('📋 Configuration Summary:', 'green');
    log(`Consumer Key: ${consumerKey ? '***' + consumerKey.slice(-4) : 'NOT SET'}`);
    log(`Shortcode: ${shortcode}`);
    log(`Base URL: ${baseUrl}`);
    log('');

    const confirm = await question(rl, 'Is this information correct? (y/N): ');
    if (confirm.toLowerCase() !== 'y' && confirm.toLowerCase() !== 'yes') {
      log('Setup cancelled.', 'red');
      rl.close();
      return;
    }

    // Create .env file content
    const envContent = `# M-Pesa API Configuration
# Generated by setup-mpesa.js

# M-Pesa API Credentials
MPESA_CONSUMER_KEY=${consumerKey}
MPESA_CONSUMER_SECRET=${consumerSecret}

# M-Pesa Business Configuration
MPESA_SHORTCODE=${shortcode}
MPESA_BUSINESS_SHORTCODE=${shortcode}
MPESA_PASSKEY=${passkey}

# Application Base URL
NEXT_PUBLIC_BASE_URL=${baseUrl}

# Callback URL (optional - will use NEXT_PUBLIC_BASE_URL if not set)
MPESA_CALLBACK_URL=${baseUrl}/api/mpesa-c2b-callback

# Note: Add your Firebase configuration here if not already set
`;

    // Write .env file
    fs.writeFileSync(envPath, envContent);
    log('✅ .env file created successfully!', 'green');
    log('');

    // Next steps
    log('📋 Next Steps:', 'blue');
    log('1. Add your Firebase configuration to the .env file if not already set', 'cyan');
    log('2. Run the C2B registration script: node register-c2b.js', 'cyan');
    log('3. Test the M-Pesa integration with a small amount', 'cyan');
    log('4. Deploy your application with the environment variables', 'cyan');
    log('');

    // Ask if user wants to run C2B registration
    const runC2B = await question(rl, 'Do you want to run C2B registration now? (y/N): ');
    if (runC2B.toLowerCase() === 'y' || runC2B.toLowerCase() === 'yes') {
      log('');
      log('🔄 Running C2B registration...', 'yellow');
      rl.close();
      
      // Run C2B registration
      require('./register-c2b.js');
    } else {
      log('');
      log('💡 You can run C2B registration later with: node register-c2b.js', 'cyan');
      rl.close();
    }

  } catch (error) {
    log(`❌ Setup failed: ${error.message}`, 'red');
    rl.close();
    process.exit(1);
  }
}

// Validation function
function validateSetup() {
  log('🔍 Validating M-Pesa Setup...', 'blue');
  
  const envPath = path.join(process.cwd(), '.env');
  if (!fs.existsSync(envPath)) {
    log('❌ .env file not found. Run setup-mpesa.js first.', 'red');
    return false;
  }

  // Load environment variables
  require('dotenv').config();

  const requiredVars = [
    'MPESA_CONSUMER_KEY',
    'MPESA_CONSUMER_SECRET', 
    'MPESA_SHORTCODE',
    'MPESA_PASSKEY'
  ];

  const missing = requiredVars.filter(varName => !process.env[varName]);
  
  if (missing.length > 0) {
    log(`❌ Missing required environment variables: ${missing.join(', ')}`, 'red');
    return false;
  }

  log('✅ All required environment variables are set!', 'green');
  return true;
}

// Main execution
if (require.main === module) {
  const command = process.argv[2];
  
  if (command === 'validate') {
    validateSetup();
  } else {
    setupMpesa();
  }
}

module.exports = { setupMpesa, validateSetup }; 